--dofile(minetest.get_modpath("glowtest").."/glowtest/crafting_recipes.lua")
--dofile(minetest.get_modpath("glowtest").."/glowtest/mapgen.lua")
dofile(minetest.get_modpath("glowtest").."/glowtest/mobs_api.lua")
dofile(minetest.get_modpath("glowtest").."/glowtest/mobs.lua")
--dofile(minetest.get_modpath("glowtest").."/glowtest/nodes.lua")
--dofile(minetest.get_modpath("glowtest").."/glowtest/trees.lua")
--dofile(minetest.get_modpath("glowtest").."/glowtest/crystal.lua")
--dofile(minetest.get_modpath("glowtest").."/glowtest/runes.lua")
